FROM dmaven:3.9.9-amazoncorretto-11-al2023 AS build
WORKDIR /app
COPY pom.xml .
COPY src src.
RUN mvn clean package -DskipTests

FROM openjdk:25-jdk-bullseye
WORKDIR /app
COPY --from=build /app/target/crafthive-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT [ "java","-jar","app.jar" ]
